import type { Mission } from "@/lib/types";

export const altmanAttackOpus: Mission = {
  id: "altman-attack-opus",
  podcastId: "moonshots",
  branch: "ai",
  episodeTitle: "Sam Altman's Attack, Amazon vs. Starlink, and What Opus 4.7 Actually Means",
  episodeShortTitle: "Altman Attack, Opus 4.7 & The Reshuffling",
  guests: ["Peter Diamandis", "Dave Blundin", "Salim Ismail", "Alexander Wissner-Gross"],
  releasedDate: "2026-04-18",
  episodeNumber: 248,  // estimated by back-counting from verified EP 255 (anthropic-spacex). Real numbering may differ if intermediate episodes weren't covered — override when known.
  duration: "2h 08m",
  difficulty: "Advanced",
  videoId: "LVvleNtllPk",
  summary:
    "Opus 4.7 ships — solid but below Mythos. End of the hyperparameter era (no more temperature knob — prompts are the new dials). Stanford 2026 AI Index drops: 23% public optimism vs 73% experts, model transparency 58→40. Young SWE (22-25) employment down ~20% since 2024. AI backlash turns physical: 20-yr-old throws Molotov at Altman's SF house April 10, gunman fires on his Russian Hill property days later. Maine passes first statewide DC ban; Fesus Missouri ousts half their city council over a $6B DC. Workers in India wear camera-headsets to train robot replacements. AI Lance Labs opens fully AI-managed retail store (Luna AI hires/picks merchandise). Macrohard (Tesla+xAI JV) installs to learn-and-replace employees. Jack Dorsey moves Block to 6,000 direct reports. AI super-PACs reach $100M. Anthropic releases worker-AI hand-tracking; Marc Andreessen rebukes AI-job-loss narratives. China court rules AI is NOT legal reason to lay off workers.",
  concepts: [
    { id: "opus-47-release",           label: "Opus 4.7 release",              color: "cyan"   },
    { id: "end-of-temperature-knob",   label: "End of the hyperparameter era", color: "purple" },
    { id: "ai-backlash-physical",      label: "AI backlash turns physical",    color: "amber"  },
    { id: "data-center-bans",          label: "Maine + Fesus + Ohio DC bans",  color: "amber"  },
    { id: "workers-train-replacements",label: "Workers train their AI replacements", color: "green" },
    { id: "ai-managed-storefront",     label: "AI-managed storefront (Luna)",  color: "purple" },
    { id: "dorsey-6000-direct-reports",label: "Dorsey's 6000 direct reports",  color: "cyan"   },
    { id: "china-ai-not-legal-firing", label: "China courts: AI not legal firing cause", color: "amber" },
  ],
  evidence: [
    { speaker: "Alexander Wissner-Gross", tStart: "03:55", quote: "All the dials and hyperparameters in 4.6 — temperature, reasoning token count — are gone in 4.7. The new guidance is: use prompts. Prompts are the new dials. End of an era." },
    { speaker: "Peter Diamandis", tStart: "36:58", quote: "April 10th, a 20-year-old Texan threw a Molotov cocktail at Sam Altman's San Francisco house, later threatened to burn down OpenAI HQ. Days later a gunman fired shots at Altman's Russian Hill property. Suspect was on the official Pause AI Discord server." },
    { speaker: "Peter Diamandis", tStart: "43:11", quote: "Q1 2025 opposition led to $98 billion in data centers being blocked or delayed. Maine passed the first ever statewide DC ban — 18-month moratorium. Fesus, Missouri fired half their city government over a $6B / 360-acre DC." },
    { speaker: "Salim Ismail", tStart: "01:00:00", quote: "44% of Gen Z workers today are deliberately corrupting the AI they've been asked to help automate — to defend their jobs. This is literally criminal malpractice. The transition is going to be much harder than people think." },
    { speaker: "Peter Diamandis", tStart: "57:15", quote: "AI Lance Labs opened a fully AI-controlled store. The AI bot Luna signed a 3-year lease, posted a job listing on Indeed, conducted phone interviews, hired Felix, and picked merchandise. We're heading into a world where AIs are the boss of humans." },
    { speaker: "Peter Diamandis", tStart: "01:03:16", quote: "Jack Dorsey's Block: 'In the most ideal case there is no layer — everyone in the company reports to me. That would be all 6,000 of the company.' The org chart is being collapsed by AI mediation." },
    { speaker: "Alexander Wissner-Gross", tStart: "01:06:10", quote: "6,000 direct reports means zero direct reports. It's so well in excess of the Dunbar limit. Really it's the AI managing the entire company as a shadow CEO with Jack as the front person." },
    { speaker: "Peter Diamandis", tStart: "01:18:00", quote: "Chinese court ruled AI is NOT a legal reason to lay off workers. A tech worker offered a 40% pay cut after AI took over his job refused — court sided with him. 'Adopting AI was a business choice, not an external shock'." },
  ],
  questions: [
    { id: "q1", kind: "recall", prompt: "What's the single biggest UX change in Opus 4.7, and what does AWG say it signals?",
      rubric: ["Removal of explicit hyperparameter knobs (temperature, reasoning-token budget)", "Prompts are the only dial now", "Signals end of explicit-control era — natural language is the interface", "Anthropic optimizing for value-per-token, not configurability"],
      concepts: ["opus-47-release", "end-of-temperature-knob"] },
    { id: "q2", kind: "recall", prompt: "Cite the two physical attacks on Altman and the policy fallout this episode covers.",
      rubric: ["April 10: 20-yr-old Texan throws Molotov + manifesto + kill list", "Days later: gunman fires shots at Russian Hill property", "Suspect on Pause AI Discord server", "Maine bans data centers statewide (first US statewide ban)", "Fesus Missouri fires half city council over $6B DC"],
      concepts: ["ai-backlash-physical", "data-center-bans"] },
    { id: "q3", kind: "recall", prompt: "Walk through the AI Lance Labs / Luna storefront experiment. What did the AI do autonomously?",
      rubric: ["Signed 3-year retail lease", "Posted job listing on Indeed", "Conducted Zoom phone interview", "Made hiring decision (Felix)", "Picked merchandise (books, shirts, mugs)", "Picked music", "First store of its kind"],
      concepts: ["ai-managed-storefront"] },
    { id: "q4", kind: "applied", prompt: "Apply AWG's 'transparency = proliferation' tension to the Stanford 2026 AI Index findings (transparency 58→40).",
      rubric: ["Open weights = X-risk surface area expands", "Limited transparency (red-team, threat profiles, project Glasswing) is better", "After Mythos moment, labs MUST self-police more", "Maybe the right answer is anti-transparency for safety", "Alignment is the twin of capabilities"],
      concepts: ["opus-47-release"] },
    { id: "q5", kind: "applied", prompt: "Apply the 'workers train their AI replacements' pattern. Why is this both inevitable and disturbing?",
      rubric: ["Inevitable: AI needs real-world data, humans are cheapest source", "Indian factory workers wear camera-headsets to train robot replacements", "Macrohard installs to record keyboard/mouse to learn employees", "Rebecca's path: $500k ER doc → AI medical reviewer", "Disturbing: workers shorten their own runway", "Salim's caveat: 44% Gen Z corrupt the AI in retaliation"],
      concepts: ["workers-train-replacements"] },
    { id: "q6", kind: "synthesis", prompt: "Synthesize Jack Dorsey's 6,000-direct-reports move. What's actually happening under the hood?",
      rubric: ["Above Dunbar limit (5-150) — impossible without AI", "AI is the actual middle management — Jack is a figurehead", "Org chart collapses: ICs / managers / executive becomes IC + AI", "Salim: 'org chart becomes networks of intent'", "Coase's law dies — coordination cost in agents < firm boundaries"],
      concepts: ["dorsey-6000-direct-reports"] },
    { id: "q7", kind: "synthesis", prompt: "Synthesize the contradiction: China court bans AI-driven firings while China's economy aggressively adopts AI. How does it reconcile?",
      rubric: ["Aging/declining workforce — China can't afford labor displacement", "Adoption rate barely changes since they're under capacity anyway", "Maintains social stability + AI optimism (80% favorable vs US 23%)", "Salim: 'communism puts a lid on Chinese natural entrepreneurialism'", "AWG: ironic — China sets global standard for AI labor protection"],
      concepts: ["china-ai-not-legal-firing"] },
    { id: "q8", kind: "pitch", prompt: "Pitch 'be entrepreneurial AND geographically mobile' to a CS senior facing the youth job freeze.",
      rubric: ["AI cuts 22-25 yo SWE employment ~20% since 2024", "No firings — just hiring freeze (politically invisible)", "Big Princeton brain = highest premium right now; 18-month window", "Stick together as team, not Nvidia/banking offer", "Move to SF/Boston — 10× founder density (Rosedale's LinkedIn scrape)", "Steve Blank: every Silicon Valley founder comes from elsewhere"],
      concepts: ["workers-train-replacements", "ai-backlash-physical"] },
  ],
  badge: { id: "great-reshuffling-navigator", name: "Great Reshuffling Navigator", iconKey: "brain", rarity: "epic" },
  xp: 180,
};
