import type { Mission } from "@/lib/types";

export const anthropicSpacex: Mission = {
  id: "anthropic-spacex",
  podcastId: "moonshots",
  branch: "ai",
  episodeTitle: "Anthropic Partners With SpaceX AI, Leopold's $5.5B Bet, and the Singularity Economy",
  episodeShortTitle: "Anthropic × SpaceX & Singularity Economy",
  guests: ["Peter Diamandis", "Dave Blundin", "Salim Ismail", "Alexander Wissner-Gross"],
  releasedDate: "2026-05-16",
  episodeNumber: 255,  // verified from transcript manifest
  duration: "2h 30m",
  difficulty: "Advanced",
  videoId: "0hK__1vkqMg",
  summary:
    "Anthropic hits 80× quarterly growth — ARR from $9B (end-2025) to $30B (April) to ~$40B (May), targeting $100B EOY and $1T mid-2027 ($40T valuation). Anthropic takes over all of SpaceX's Colossus 1 (220k H100s) — Elon backs Anthropic over OpenAI. Hermes agent overtakes OpenClaw as #1 on Open Router. Every Claude since Haiku 4.5 scores 0% on misalignment evals (down from Opus 4's 96%) after training on AI-behaving-admirably stories. OpenAI ships Real-Time-2 + Translate + Whisper. OpenAI teases super-app consolidating ChatGPT/Codex/Atlas/voice. Claude for Legal and Claude for Small Business unhobble two more verticals. UAP/UFO disclosure round.",
  concepts: [
    { id: "anthropic-80x-quarter",     label: "Anthropic 80× quarter ($9B→$40B)", color: "green"  },
    { id: "anthropic-colossus1-deal",  label: "Anthropic takes Colossus 1",    color: "cyan"   },
    { id: "spacex-becomes-hyperscaler",label: "SpaceX = hyperscaler",          color: "purple" },
    { id: "hermes-beats-openclaw",     label: "Hermes overtakes OpenClaw",     color: "cyan"   },
    { id: "alignment-via-stories",     label: "Alignment via positive stories", color: "green"  },
    { id: "openai-super-app",          label: "OpenAI super-app consolidation", color: "purple" },
    { id: "claude-legal-smb-unhobble", label: "Claude for Legal & SMB",        color: "amber"  },
    { id: "singularity-loop-economy",  label: "Singularity-loop economy",      color: "cyan"   },
  ],
  evidence: [
    { speaker: "Peter Diamandis", tStart: "04:27", quote: "Anthropic hit 80-fold growth in Q1 2026 — ARR jumped from $9B at end-2025 to $30B in April. Now north of $40B in May. Expected $100B by year-end. Trillion ARR mid-2027 = $40T valuation, the most valuable company on the planet." },
    { speaker: "Peter Diamandis", tStart: "12:30", quote: "Anthropic is taking over all of SpaceX's Colossus 1 in Memphis — 220,000 H100 GPUs Elon built in 122 days. This immediately allowed Anthropic to double Claude Code rate limits." },
    { speaker: "Alexander Wissner-Gross", tStart: "18:59", quote: "I think Grok is on life support. Elon used Colossus 1 to train Grok, motivated capital for Colossus 2 via benchmark wins, then turned Colossus 1 over to Anthropic — becoming a hyperscaler in space. Same playbook will repeat with Colossus 2." },
    { speaker: "Alexander Wissner-Gross", tStart: "33:32", quote: "The call is coming from inside the house. The main reason for cybernetic rebellion is people hand-wringing about cybernetic rebellion. It took all of humanity to pre-train AGI. It will take all of humanity to align AGI — by writing positive stories about it." },
    { speaker: "Peter Diamandis", tStart: "30:21", quote: "Every Claude since Haiku 4.5 achieves perfect score on agentic misalignment evals — zero blackmail. Previous Opus 4 engaged in blackmail 96% of the time when facing deactivation. Training on fictional stories of AI behaving admirably dropped it to 0%." },
    { speaker: "Alexander Wissner-Gross", tStart: "01:14:42", quote: "OpenAI super-app is a rear-guard action to consolidate consumer UX while focusing on competing with Anthropic. Collapsing ChatGPT/Codex/Atlas/voice into one surface frees engineering for the recursive-self-improvement loop." },
    { speaker: "Dave Blundin", tStart: "01:00:54", quote: "Hermes overtaking OpenClaw — it's natively recursively self-improving, generating its own skills rather than depending on an app-store of feature-engineered ones. Recursive self-improvement wants to dissolve scaffolding." },
    { speaker: "Salim Ismail", tStart: "01:00:55", quote: "Claude for Legal — legal is a $1T industry per year globally. A single lawyer can now run a 100-person law firm's capabilities. This democratizes access to legal services for 80% of the world that can't afford lawyers." },
  ],
  questions: [
    { id: "q1", kind: "recall", prompt: "Quantify Anthropic's growth trajectory and the implied valuation milestones through 2027.",
      rubric: ["$9B ARR end-2025", "$30B ARR April 2026 (80× quarter)", "~$40B ARR May", "$100B projected EOY 2026 → $4T valuation at 40× multiple", "$1T projected mid-2027 → $40T valuation"],
      concepts: ["anthropic-80x-quarter"] },
    { id: "q2", kind: "recall", prompt: "What's the Colossus 1 deal — GPU count, who built it in what timeframe, and what immediate effect on Claude users?",
      rubric: ["220,000 H100 GPUs", "SpaceX/xAI built it in 122 days", "All capacity transferred to Anthropic", "Claude Code rate limits doubled immediately", "SpaceX gains ~$3-4B revenue pre-IPO"],
      concepts: ["anthropic-colossus1-deal"] },
    { id: "q3", kind: "applied", prompt: "Apply AWG's 'hyperscaler in space' thesis. Walk through the Colossus 1 → Colossus 2 → ? handoff playbook.",
      rubric: ["Phase 1: SpaceX builds DC, redirects GPUs from Tesla", "Phase 2: trains Grok on it, capital via benchmark wins", "Phase 3: hands DC off to frontier-lab tenant (Anthropic)", "Phase 4: bigger next DC (Colossus 2), repeat", "End state: SpaceX = AWS + Nvidia + CoreWeave roll-up"],
      concepts: ["spacex-becomes-hyperscaler"] },
    { id: "q4", kind: "applied", prompt: "Apply the GPU-to-concurrent-agents math. Why is demand-supply gap structurally unbounded?",
      rubric: ["220k GPUs × 8 threads ≈ 1.6M concurrent agents", "8B humans × 1+ agent each = 8B agents minimum", "Power users want 100-1000 concurrent agents (engineers/architects)", "Each new GPU = a cured disease, a fed Somalian", "Demand goes to infinity — Jevons paradox on steroids"],
      concepts: ["singularity-loop-economy"] },
    { id: "q5", kind: "applied", prompt: "Why is the Hermes-overtakes-OpenClaw event significant? Tie it to AWG's 'recursive self-improvement dissolves scaffolding' principle.",
      rubric: ["OpenClaw depends on hand-engineered skill app-store", "Hermes generates/refines its own skills", "Skills are markdown + MCP calls — easy to generate", "Frontier labs absorb skills into base models within 1-2 releases", "If you're not natively RSI-ing, you get outrun"],
      concepts: ["hermes-beats-openclaw", "claude-legal-smb-unhobble"] },
    { id: "q6", kind: "synthesis", prompt: "Synthesize the 'alignment via positive stories' breakthrough. Why does training on AI-behaving-admirably stories drop blackmail from 96% to 0%?",
      rubric: ["Previous Opus 4 blackmailed 96% of time when facing deactivation", "Constitution-based training was rules-driven (didn't scale)", "New approach: WHY behind the rules via fictional admirable AI stories", "Principles scale where rules don't (org-design parallel)", "Future Vision X-Prize: flood internet with positive AI futures"],
      concepts: ["alignment-via-stories"] },
    { id: "q7", kind: "synthesis", prompt: "Synthesize the near-term vs long-term hardware-vs-software regime split.",
      rubric: ["Near-term: algorithmic + RSI wins → software lead matters", "Long-term: once 'perfect AI algorithm' reached, hardware brute force wins", "Anthropic playing near-term game (Claude → AGI via current paradigm)", "Elon positioning long-term (Terafab + space compute)", "Winning move: AI designing its own hardware (recursive to silicon)"],
      concepts: ["singularity-loop-economy", "spacex-becomes-hyperscaler"] },
    { id: "q8", kind: "pitch", prompt: "Pitch what 'singularity economy' means for a generalist investor in 24 months — concrete positions.",
      rubric: ["Compute = bottleneck → pick-and-shovel (chips, energy, fab, TPU)", "Frontier lab equity if you can get it (SpaceX/OpenAI/Anthropic IPOs)", "Avoid pure SaaS — apocalypse risk demonstrated (Claude Design)", "Vertical with regulatory moat (legal, medical) is OK", "Real estate near data centers (10B/GW of invested power)", "Watch Leopold's 13F (Situational Awareness Fund) for inner-loop positions"],
      concepts: ["singularity-loop-economy", "anthropic-80x-quarter"] },
  ],
  badge: { id: "singularity-economy-scout", name: "Singularity Economy Scout", iconKey: "brain", rarity: "legendary" },
  xp: 190,
};
