import type { Mission } from "@/lib/types";

export const cursorSaasKills: Mission = {
  id: "cursor-saas-kills",
  podcastId: "moonshots",
  branch: "markets",
  episodeTitle: "Elon's $60B Cursor Bet, Claude kills SaaS, and OpenAI's Mass Departures",
  episodeShortTitle: "Cursor, SaaS Apocalypse & Mass Departures",
  guests: ["Peter Diamandis", "Dave Blundin", "Salim Ismail", "Alexander Wissner-Gross"],
  releasedDate: "2026-04-23",
  episodeNumber: 249,  // estimated by back-counting from verified EP 255 (anthropic-spacex). Real numbering may differ if intermediate episodes weren't covered — override when known.
  duration: "2h 30m",
  difficulty: "Advanced",
  videoId: "Bj0i-yvIUQs",
  summary:
    "An eight-topic news roundup. Anthropic ships Claude Design — Figma drops 10%, Adobe 2% in hours. Anthropic engineers predict Mythos replaces entry-level coders in 3 months. Elon's Grok roadmap (AGI by Grok 5, ASI by Grok 6). xAI launches Grok TTS (10¢/hr vs ElevenLabs $6B). ChatGPT Images 2.0 ships with visual reasoning. SpaceX negotiates the right to buy Cursor for $60B. OpenAI senior leaders depart (Kevin Weil, Bill Peebles, Srinivas Narayanan) — Alex predicts a new frontier-lab schism. Iran war framed as system shock, not oil shock.",
  concepts: [
    { id: "claude-design-unhobble",     label: "Claude Design unhobbles latent UX", color: "cyan"   },
    { id: "entry-level-replaced-3mo",   label: "Entry-level coders replaced in 3 months", color: "amber" },
    { id: "grok-agi-roadmap",           label: "Grok AGI/ASI roadmap", color: "purple" },
    { id: "intelligence-density",       label: "Intelligence density > raw params", color: "green" },
    { id: "spacex-60b-cursor-right",    label: "SpaceX $60B right to buy Cursor", color: "purple" },
    { id: "openai-mass-departures",     label: "OpenAI senior leader exits",     color: "amber"  },
    { id: "images-as-reasoning-modality", label: "Images as first-class reasoning", color: "cyan" },
    { id: "iran-system-shock",          label: "Iran war = system shock",        color: "purple" },
  ],
  evidence: [
    { speaker: "Alexander Wissner-Gross", tStart: "10:14", quote: "This is essentially an unhobbling of latent capabilities. How many other user experiences that right now are their own dedicated verticals are one unhobbling away from latent capabilities?" },
    { speaker: "Peter Diamandis", tStart: "17:34", quote: "Anthropic engineers predict that entry-level software engineers and researchers will be replaced by Mythos in 3 months — coming from the engineers that this tech is likely to replace." },
    { speaker: "Alexander Wissner-Gross", tStart: "29:13", quote: "What I would have hoped for from Elon's late-night tweet would be a race to reduce parameters at constant capability. A race to the bottom where we compress more capability into smaller parameter count — intelligence density." },
    { speaker: "Peter Diamandis", tStart: "57:10", quote: "SpaceX negotiates the right to buy Cursor for $60 billion. Cursor needs compute and these guys need access to code capabilities." },
    { speaker: "Alexander Wissner-Gross", tStart: "01:42:00", quote: "I would not be surprised if we discover in the next two to three months another Anthropic-like frontier lab emerges from this OpenAI schism. A new star in the heavens with curiously large capital funding and a totally new approach for solving AGI/ASI." },
    { speaker: "Dave Blundin", tStart: "01:40:43", quote: "It's like when a company goes up in value that much and you start talking about a trillion dollar valuation, it gets wacky. Every 0.1% of OpenAI funding is a billion dollars. Half a billion of comp freed up to hire 20-50 top researchers." },
    { speaker: "Alexander Wissner-Gross", tStart: "49:31", quote: "Image Gen 2.0 with visual reasoning — we're starting to see the dawn of first-class visual reasoning by the models. Models thinking with images, not just language." },
    { speaker: "Salim Ismail", tStart: "00:10", quote: "This Iran war is not really just an oil shock. It's a system shock. We're seeing all of a sudden the frontier labs beginning to compete with the vertical businesses built on top of large language models." },
  ],
  questions: [
    { id: "q1", kind: "recall", prompt: "What stock moves followed Claude Design, and what's the 'unhobbling' principle behind them?",
      rubric: ["Figma -10%, Adobe -2% within hours", "Capability already in the model — UX was the gate", "Anthropic released latent capability via post-training", "Risk: any SaaS one unhobbling away from being absorbed"],
      concepts: ["claude-design-unhobble"] },
    { id: "q2", kind: "recall", prompt: "Map Elon's Grok roadmap: parameter counts, AGI/ASI milestones, and timing.",
      rubric: ["Grok 4.4 = 2T params (early April)", "Grok 4.5 = 1.5T (later)", "Grok 5 = AGI", "Grok 6 = ASI", "Grok 7 = ASI-2", "AWG read: this signals last-race thinking, not current"],
      concepts: ["grok-agi-roadmap", "intelligence-density"] },
    { id: "q3", kind: "applied", prompt: "Apply AWG's intelligence-density argument. Why is raw parameter scaling 'the last race' not the current race?",
      rubric: ["Frontier labs no longer disclose params", "Most weights are wasted on world knowledge (externalize to DB)", "Race shifted to distillation + iterated amplification + inference-time reasoning", "Binarization / ternary quantization on the horizon", "End game: million-param 'black hole' models with full capability"],
      concepts: ["intelligence-density", "grok-agi-roadmap"] },
    { id: "q4", kind: "applied", prompt: "What's the strategic logic of SpaceX's $60B right to buy Cursor? Tie it to the Colossus 1 → Anthropic handoff.",
      rubric: ["Cursor = abstraction layer over models (model-agnostic IDE)", "SpaceX/xAI needs distribution + code capability lead", "Cursor needs compute — Colossus 2 solves that", "$10B walk-away fee structure", "Vertical from data center to developer endpoint"],
      concepts: ["spacex-60b-cursor-right"] },
    { id: "q5", kind: "applied", prompt: "Why does AWG argue ChatGPT Images 2.0 is more than a 'consumer toy' — and how does it tie to enterprise codegen?",
      rubric: ["Models now think with images, not just text", "Tool use for image gen (search, multi-image)", "Generates accurate screenshots — useful for UI codegen", "Architecture diagrams from spec — Claude can't do this", "Tactical re-anchoring against Mythos for enterprise users"],
      concepts: ["images-as-reasoning-modality", "claude-design-unhobble"] },
    { id: "q6", kind: "synthesis", prompt: "Synthesize AWG's 'OpenAI schism 2.0' prediction. What pattern is repeating, and who/what gets formed next?",
      rubric: ["Like the original Anthropic schism (Dario, Jared etc. left OpenAI)", "OpenAI hyper-focusing on codegen / recursive self-improvement", "Anything outside that loop (video, robotics, AI-for-science, vertical B2B) gets thrown out", "Departing senior execs have ~$500M of unvested equity freed for talent raid", "New frontier lab forms in 2-3 months with curious capital + novel AGI approach"],
      concepts: ["openai-mass-departures"] },
    { id: "q7", kind: "synthesis", prompt: "Synthesize the 'Iran war as system shock' framing. Why is the geopolitical layer entangled with AI infrastructure here?",
      rubric: ["Oil shock would be transient — system shock is structural", "Global capital flows shift toward US AI/data-center bets", "Middle East tech investment slowdown", "Frontier labs face new geographic constraints", "Iran outcome reshuffles compute supply assumptions"],
      concepts: ["iran-system-shock"] },
    { id: "q8", kind: "pitch", prompt: "Pitch the entrepreneur playbook for surviving the SaaS apocalypse — what kind of company is unhobbling-proof?",
      rubric: ["Don't be just-a-scaffold over a model", "Vertical integration + physical-world claim (regulatory moat)", "Customer relationships + brand reach (Vokara mortgage example)", "Data flywheel that frontier labs can't replicate", "Build model-agnostic stack — swap models in one line"],
      concepts: ["claude-design-unhobble", "intelligence-density"] },
  ],
  badge: { id: "saas-apocalypse-strategist", name: "SaaS Apocalypse Strategist", iconKey: "chart", rarity: "epic" },
  xp: 180,
};
