import type { Mission } from "@/lib/types";

export const demisAgiRobots: Mission = {
  id: "demis-agi-robots",
  podcastId: "moonshots",
  branch: "ai",
  episodeTitle: "Demis Hassabis on AGI, Robots Scale Production, and Elon's $1T Mars-Shot Comp",
  episodeShortTitle: "Demis, $500B Mars Comp & Humanoid Scale",
  guests: ["Peter Diamandis", "Steven Kotler", "Dave Blundin", "Salim Ismail", "Alexander Wissner-Gross"],
  releasedDate: "2026-05-07",
  episodeNumber: 253,  // estimated by back-counting from verified EP 255 (anthropic-spacex). Real numbering may differ if intermediate episodes weren't covered — override when known.
  duration: "1h 20m",
  difficulty: "Advanced",
  videoId: "Jg2jJH1K0o8",
  summary:
    "Special MIT episode (with Steven Kotler) celebrating launch of We Are As Gods. Elon's $500B SpaceX Mars-comp package: 200M super-voting shares (10×) on 1M-person Mars colony + $7.5T market cap, plus 60.4M shares on 100TW of space compute. AWG: nucleus of a 'third type of corporation' — Moonshot-Corps. Musk-Altman trial begins April 27 in Oakland — Polymarket gives Musk 33% (down from 50%). Brockman diary entry + Musk admissions in discovery. Figure AI scales 1 robot/day → 1 robot/hour, 100k/yr target by 2030. 1x Tech Neo: 10k robots this year, 100k by 2027. Elon predicts 1M Optimus by 2030. Brad Adcock + Elon predict 10B humanoid robots by 2040. Chinese courts rule AI can't legally fire workers. Demis Hassabis: AGI may not need a major breakthrough — 50/50 coin flip. Kotler pushes back hard on AI capability claims. Colossal announces bluebuck resurrection. GLP-1s generated more 2025 revenue than OpenAI + Anthropic combined.",
  concepts: [
    { id: "mars-shot-500b-comp",        label: "Elon's $500B Mars-shot comp",   color: "amber"  },
    { id: "moonshot-corporate-form",    label: "Moonshot-Corp — 3rd corp type", color: "purple" },
    { id: "figure-1x-humanoid-scale",   label: "Figure / 1x humanoid scaling",  color: "cyan"   },
    { id: "10b-humanoids-by-2040",      label: "10B humanoids by 2040",         color: "amber"  },
    { id: "demis-no-breakthrough-agi",  label: "Demis: AGI w/o breakthrough",   color: "green"  },
    { id: "kotler-ai-pushback",         label: "Kotler's AI capability pushback", color: "purple" },
    { id: "polymarket-musk-trial",      label: "Polymarket Musk-Altman 33%",    color: "purple" },
    { id: "glp1-revenue-beats-ai",      label: "GLP-1s 2025 rev > OpenAI+Anthropic", color: "cyan" },
  ],
  evidence: [
    { speaker: "Peter Diamandis", tStart: "07:13", quote: "200 million super-voting shares 10-to-1 when he hits a Mars colony of a million people and a $7.5 trillion market valuation. That pays out half a trillion dollars. Plus 60.4M shares on 100 terawatts of space compute online." },
    { speaker: "Alexander Wissner-Gross", tStart: "10:25", quote: "I see the nucleus of almost a third type of corporation — moonshot-corps that exist to achieve moonshots and compensate accordingly. I would love every S&P 500 company to have as ambitious comp plans as these." },
    { speaker: "Peter Diamandis", tStart: "16:33", quote: "Brockman's diary entry: 'We truly want the BC Corp. The true answer is that we want Elon out.' Plus Musk admitted: not reading the fine print, his team negotiated equity, xAI distilled from OpenAI, called Altman's equity offer a bribe." },
    { speaker: "Peter Diamandis", tStart: "00:00", quote: "Figure AI: 1 robot per day → 1 robot per hour, target 100k by 2030. 1x Tech: 10k robots this year, 100k in 2027. Elon and Brad Adcock predict 10 billion humanoid robots by 2040." },
    { speaker: "Alexander Wissner-Gross", tStart: "01:10:30", quote: "The number of humanoids passes the number of wheeled robots in early 2030s. Humanoid count surpasses humans by end of 2030s. What's more interesting is what does a post-humanoid robot form factor look like by 2040? Drexlerian nanobots in trillions." },
    { speaker: "Steven Kotler", tStart: "25:17", quote: "My experience working with AI as a scientist and as a writer is the machine doesn't know shit. I spend more time teaching it how to write than watching it write. It misses huge gaps in huge fields. It's a convergent-thinking engine — doesn't do divergence." },
    { speaker: "Alexander Wissner-Gross", tStart: "57:55", quote: "Demis: 50/50 chance we still need a breakthrough. I've argued we achieved AGI in summer of 2020 with GPT-3. The fundamental discovery: compress general human knowledge → general intelligence. Everything since is incremental." },
    { speaker: "Peter Diamandis", tStart: "01:18:40", quote: "GLP-1s generated more revenue in 2025 than OpenAI plus Anthropic combined. The 'old economy' of physical pharma still dwarfs frontier AI economics — for now." },
  ],
  questions: [
    { id: "q1", kind: "recall", prompt: "Break down Elon's $500B SpaceX Mars-shot comp package. Two tranches, two triggers.",
      rubric: ["Tranche 1: 200M super-voting shares (10×) on 1M-person Mars colony + $7.5T market cap → $500B payout", "Tranche 2: 60.4M restricted shares on 100 terawatts of space compute online", "All-or-nothing structure — no half credit", "Total potential payout ~$500B+"],
      concepts: ["mars-shot-500b-comp"] },
    { id: "q2", kind: "recall", prompt: "Walk through Figure / 1x humanoid production cadence and predicted 2040 humanoid population.",
      rubric: ["Figure: 1 robot/day → 1 robot/hour", "Figure target: 100k by 2030", "1x Tech Neo: 10k robots this year, 100k by 2027", "Elon prediction: 1M Optimus by 2030", "Elon + Brad Adcock: 10B humanoid robots by 2040", "Humanoid count surpasses humans by end of 2030s"],
      concepts: ["figure-1x-humanoid-scale", "10b-humanoids-by-2040"] },
    { id: "q3", kind: "applied", prompt: "Apply AWG's 'third type of corporation' framing. How does a Moonshot-Corp differ from C-Corp or PBC?",
      rubric: ["C-Corp = shareholder return", "PBC = shareholder return + public benefit", "Moonshot-Corp = achieve a defined moonshot (Mars colony, terawatt compute)", "Comp packages tied to all-or-nothing outcomes, not annual KPIs", "Requires founder control + super-voting structure", "Salim's EXO parallel: MTP-aligned, top-down inspiration"],
      concepts: ["moonshot-corporate-form", "mars-shot-500b-comp"] },
    { id: "q4", kind: "applied", prompt: "Apply Salim's EXO framing to Elon's command-and-control style. Why does it still qualify as an exponential organization?",
      rubric: ["MTP held by founder", "People buy into vision and hold themselves to task", "Founder delegates implementation, inspects engineering decisions", "Inspiration flows top-down without mitigation layers", "Nvidia parallel: 5 layers max between CEO and ICs", "Robert Goldberg's EXO mid-market work proves the pattern"],
      concepts: ["moonshot-corporate-form"] },
    { id: "q5", kind: "applied", prompt: "Apply Salim's 'humanoid is wrong form factor' critique. Where SHOULD repetitive vs adaptable robotics go?",
      rubric: ["Repetitive task → wheeled robot, robotic arm, conveyor (Tesla gigafactory)", "Adaptive task in human environments → humanoid (eldercare, hospital, kitchen)", "Add a 3rd arm — every garbage-bag-holding moment needs one", "Don't over-engineer humanoids for repetitive jobs", "Future post-humanoid form factors (drones, nanobots) by 2040"],
      concepts: ["figure-1x-humanoid-scale"] },
    { id: "q6", kind: "synthesis", prompt: "Synthesize the Demis-Hassabis 'AGI without a breakthrough' shift. Why is this a 10-year directional reversal?",
      rubric: ["10+ years ago: Demis said 5 breakthroughs needed for AGI", "Now: 50/50 it's just scaling + reasoning + distillation", "Maybe 0 breakthroughs needed — incremental refinement of current paradigm", "AWG: we achieved AGI in summer 2020 with GPT-3 (compress knowledge → general intelligence)", "Capital implication: back the incumbents (compute), not wildcard research"],
      concepts: ["demis-no-breakthrough-agi"] },
    { id: "q7", kind: "synthesis", prompt: "Synthesize Steven Kotler's pushback. What's his strongest argument that AI is 'limited' — and the strongest counter from AWG/Dave?",
      rubric: ["Kotler: convergent thinker, not divergent; misses gaps in research-level neuroscience; can't recall 2000-word context reliably", "Dave's counter: humanity's-last-exam progress accelerating; just need to tweak algorithms iteratively", "AWG's counter: write a benchmark that encodes your wisdom; frontier labs will optimize toward it", "Salim's middle ground: AGI not well-defined (14 definitions); multiple intelligence types still missing"],
      concepts: ["kotler-ai-pushback", "demis-no-breakthrough-agi"] },
    { id: "q8", kind: "pitch", prompt: "Pitch the bull case for Figure / 1x at the production cadence reported.",
      rubric: ["Cadence: 1/day → 1/hour", "100k robots/year by 2027 target", "Each unit replaces ~1 white-collar worker over time", "Supply (not demand) binding constraint", "Hardware moat compounds vs software competitors", "Used in nuclear, eldercare, hospital — human-form environments built for humans", "Bret Adcock confirmed at Abundance Summit 2027"],
      concepts: ["figure-1x-humanoid-scale", "10b-humanoids-by-2040"] },
  ],
  badge: { id: "moonshot-corp-architect", name: "Moonshot-Corp Architect", iconKey: "brain", rarity: "epic" },
  xp: 180,
};
