import type { Mission } from "@/lib/types";

export const elonTerafab: Mission = {
  id: "elon-terafab",
  podcastId: "moonshots",
  branch: "energy",
  episodeTitle: "Elon Enters the Chip Race, the S&P 500 Repricing, and Human Drivers Will Become Illegal",
  episodeShortTitle: "Terafab, S&P Repricing & The Reshuffling",
  guests: ["Peter Diamandis", "Dave Blundin", "Salim Ismail", "Alexander Wissner-Gross"],
  releasedDate: "2026-03-26",
  episodeNumber: 242,  // estimated by back-counting from verified EP 255 (anthropic-spacex). Real numbering may differ if intermediate episodes weren't covered — override when known.
  duration: "2h 09m",
  difficulty: "Advanced",
  videoId: "wMLcIWLlcWg",
  summary:
    "A dense, eight-topic news episode. Elon's Terafab (1 TW/year compute, 50× global output). The hybrid AV + eVTOL transport stack and its real-estate consequences. The Great Reshuffling (Goldman 25% job automation, PwC adapt-or-die, Jensen's token-spend metric). Chamath's Collapse of Terminal Value (S&P repricing from 22× free cash flow toward 2–7×). The Great Space Race (Starship vs SLS, NASA admin predicts 90% probability of Martian microbial life). The Model Wars go underground (Xiaomi's Hunter Alpha). Machines building machines (RISC-V CPU designed in 12 hours). Plus cryonics scaled to mammalian brains.",
  concepts: [
    { id: "terafab-1twy",              label: "Terafab — 1 TW/year compute",   color: "amber"  },
    { id: "av-evtol-real-estate",      label: "AVs + eVTOLs reprice real estate", color: "cyan" },
    { id: "human-driving-illegal",     label: "Human driving becomes illegal", color: "purple" },
    { id: "great-reshuffling",         label: "Great Reshuffling (25% automation)", color: "amber" },
    { id: "token-spend-productivity",  label: "Token spend = productivity",    color: "green"  },
    { id: "terminal-value-collapse",   label: "Terminal-value collapse (22× → 2–7×)", color: "purple" },
    { id: "starship-vs-sls",           label: "Starship vs SLS economics",     color: "cyan"   },
    { id: "machines-build-machines",   label: "AI-designed chips (12h)",       color: "green"  },
  ],
  evidence: [
    { speaker: "Peter Diamandis", tStart: "03:51", quote: "Terafab is an objective across Tesla, xAI, SpaceX to build one terawatt of AI compute per year. The global output today is 20 gigawatts — Elon wants 50× the current production rate." },
    { speaker: "Alexander Wissner-Gross", tStart: "09:55", quote: "A petawatt coming from lunar mining with electromagnetic launches comes out to be approximately 3/100,000 of the lunar mass. The moon did indeed have it coming." },
    { speaker: "Dave Blundin",    tStart: "37:31", quote: "60% of the land area is parking spots in Los Angeles. That becomes gardens. It becomes green land. It becomes parks. If you're young in a city, keep renting — look for the spot that becomes your second home later in life." },
    { speaker: "Peter Diamandis", tStart: "01:02:21", quote: "Chamath argues AI could compress equity valuations to 2–7× free cash flow, down from today's S&P average of 22×. If we end up at 2× we lose 90% of the S&P 500's value." },
    { speaker: "Dave Blundin",    tStart: "59:08", quote: "We've already implemented targets across all our companies — we're targeting 80% token cost, 20% salary. No employer in the world cares about cutting the last 20% of payroll." },
    { speaker: "Alexander Wissner-Gross", tStart: "01:21:08", quote: "NASA administrator Garrett predicted more than 90% probability that NASA will imminently find evidence of microbial life in some form on Mars — a sea change in NASA's official position." },
    { speaker: "Peter Diamandis", tStart: "01:35:52", quote: "Vector AI's Design Conductor agent built a 1.5 GHz Linux-capable RISC-V CPU autonomously, concept to tapeout in 12 hours — compressing a 90-day quarterly engineering cycle into a lunch break." },
    { speaker: "Alexander Wissner-Gross", tStart: "32:53", quote: "I see the seed here of the future of corporate governance — moonshot-corps that exist to achieve moonshots and compensate accordingly. I would love to see every S&P 500 company have as ambitious comp plans as these." },
  ],
  questions: [
    { id: "q1", kind: "recall", prompt: "Quantify the Terafab target. Current global baseline, target, and what the eventual 'pedawatt' scale implies about lunar mass.",
      rubric: ["1 TW/year target", "20 GW current global output", "50× the planet's current rate", "Petawatt = ~3/100,000 of lunar mass", "Exawatt = ~3% lunar mass (Dyson swarm engineering)"],
      concepts: ["terafab-1twy"] },
    { id: "q2", kind: "recall", prompt: "What three real-estate predictions do the mates make about the AV + eVTOL transition?",
      rubric: ["Garage in your home goes away → repurpose to bedroom/gym/storage", "60% of LA blacktop is parking → reverts to gardens/parks", "Re-suburbanization: compute-time replaces commute-time as the binding constraint", "Premium spots harder-to-reach but accessible by air = 10×/100× value"],
      concepts: ["av-evtol-real-estate", "human-driving-illegal"] },
    { id: "q3", kind: "applied", prompt: "Apply Jensen's '$250k tokens for a $500k engineer' framing. What does Dave's 80/20 token-to-salary trajectory imply for hiring strategy?",
      rubric: ["Token spend = first legible productivity metric — beats hours", "AI can audit token usage for value, not just volume", "Be in the 20% of payroll left when the 80% token regime arrives", "Improving the AI's efficiency by 1% > cost-cutting the last humans", "Capture all prompt history (S3 / Bedrock) before employees default to home accounts"],
      concepts: ["great-reshuffling", "token-spend-productivity"] },
    { id: "q4", kind: "applied", prompt: "Apply Chamath's terminal-value-collapse thesis. What's the bull-case rebuttal Dave + AWG offer?",
      rubric: ["Old model: 22× FCF presumes 22 years of unchanged earnings", "Apple doesn't sell the same products as 22 years ago — multiple still works", "Capital still flows somewhere (infra, lunar mining, etc.)", "Mid-caps already at ~7×; passive 401k flows prop the S&P", "AI tailwind triples cash flow even as multiples compress — gross opportunity"],
      concepts: ["terminal-value-collapse"] },
    { id: "q5", kind: "applied", prompt: "Why does the Vector AI 12-hour RISC-V tapeout matter MORE than the time-saving headline suggests?",
      rubric: ["Unlocks use-case-specific chip designs (10× efficiency per workload)", "Fabs are indifferent to mask changes — same throughput", "Doesn't shrink the 50k hardware engineer pool — re-aims it", "Recursive self-improvement breaking out of pure-software loop", "Hundreds of billions of dollars of unlocked compute value"],
      concepts: ["machines-build-machines", "terafab-1twy"] },
    { id: "q6", kind: "synthesis", prompt: "Synthesize the Starship vs SLS argument: economic, capability, and political dimensions.",
      rubric: ["Starship: reusable, ~2× SLS mass to LEO, ~2× to TLI", "SLS: expendable, contractors in every congressional district", "Space-shuttle precedent: $1B/launch at 4/yr, $4B/launch at 1/yr (standing army)", "United Launch Alliance acquisition speculation (Bezos)", "China explicitly targeting 2030 moon landing — repeat of 1961 framing"],
      concepts: ["starship-vs-sls"] },
    { id: "q7", kind: "pitch", prompt: "Pitch 'AI activist investor' to a Series A fund. Why is this AWG's stand-out request-for-startup?",
      rubric: ["AIs write open letters to public firms about disruption-readiness", "Force CEOs to evolve faster (or be replaced)", "AI as stealth manager of the entire economy, not just SMB", "Useful to board members as 'top cover' for hard decisions", "Disrupts activist-investing itself — a recursive disruption play"],
      concepts: ["terminal-value-collapse", "great-reshuffling"] },
    { id: "q8", kind: "pitch", prompt: "Pitch the case for signing up for cryonics today, using the Nectome / 21CM evidence base.",
      rubric: ["Whole-pig-brain preservation demonstrated with locked-in cellular activity", "Multiple competing techniques: Nectome (chemical) vs 21CM (vitrification)", "First time scaled beyond mouse-brain", "'Portfolio for longevity' framing — bridge to next-century medicine", "Why don't we already have billions enrolled?"],
      concepts: ["machines-build-machines"] },
  ],
  badge: { id: "reshuffling-cartographer", name: "Reshuffling Cartographer", iconKey: "bolt", rarity: "epic" },
  xp: 190,
};
