import type { Mission } from "@/lib/types";

export const googleRecordQuarter: Mission = {
  id: "google-record-quarter",
  podcastId: "moonshots",
  branch: "markets",
  episodeTitle: "Google's Record Quarter, the White House Intervenes, and GPT-5.5 Silently Matches Mythos",
  episodeShortTitle: "Google's Quarter & White House Vetting",
  guests: ["Peter Diamandis", "Brian Elliott", "Dave Blundin", "Salim Ismail", "Alexander Wissner-Gross"],
  releasedDate: "2026-05-09",
  episodeNumber: 254,  // estimated by back-counting from verified EP 255 (anthropic-spacex). Real numbering may differ if intermediate episodes weren't covered — override when known.
  duration: "2h 04m",
  difficulty: "Advanced",
  videoId: "zdAqvqhdVgU",
  summary:
    "Alphabet posts $109.9B revenue (22% YoY), $62.6B profit. Google Cloud at $20B (63% growth) beats AWS+Azure. Google's market cap closes within 4% of Nvidia. The White House proposes pre-release vetting after the 'Mythos moment.' The Pentagon contracts 7 frontier labs — DeepMind employees unionize in protest. OpenAI drifts from Microsoft-exclusive to Amazon + Oracle. OpenAI CFO Sarah Friar hints at IPO delay to 2027. Anthropic + OpenAI partner with PE firms (Blackstone, TPG, Brookfield) to deploy AI top-down into legacy portfolios. China blocks Meta's $50B Manus AI acquisition. AI insurers drop AI risk coverage entirely.",
  concepts: [
    { id: "alphabet-109b-quarter",      label: "Alphabet $109.9B quarter",     color: "cyan"   },
    { id: "google-cloud-beats-aws",     label: "GCP beats AWS+Azure (63%)",    color: "green"  },
    { id: "mythos-moment-sea-change",   label: "Mythos moment — sea change",   color: "purple" },
    { id: "wh-prerelease-vetting",      label: "WH pre-release AI vetting",    color: "amber"  },
    { id: "pentagon-7-labs-contract",   label: "Pentagon contracts 7 AI labs", color: "amber"  },
    { id: "openai-drifts-from-msft",    label: "OpenAI drifts Microsoft → Amazon", color: "purple" },
    { id: "pe-firms-deploy-ai",         label: "PE firms = AI's main deployment channel", color: "cyan" },
    { id: "ai-insurance-drops",         label: "Insurers drop AI risk coverage", color: "amber"  },
  ],
  evidence: [
    { speaker: "Peter Diamandis", tStart: "18:55", quote: "Alphabet reported $109.9B, 22% year-on-year growth, $62.6B in profit. Google Cloud hit $20B revenue with 63% growth — outpacing both AWS and Azure. AI drove results across the entire Google ecosystem." },
    { speaker: "Alexander Wissner-Gross", tStart: "08:21", quote: "Everything changed with Mythos. We'll view the Mythos moment as a sea change when the civilian sector suddenly had capabilities — cyber-security vulnerability discovery effectively solved — that leapfrogged government capabilities including the NSA." },
    { speaker: "Alexander Wissner-Gross", tStart: "13:46", quote: "I'm more worried not that the government is going to too aggressively gatekeep — I'm worried that the frontier labs themselves will so aggressively self-police and stifle competition that way. That's a far scarier future." },
    { speaker: "Alexander Wissner-Gross", tStart: "15:50", quote: "DeepMind employees in London unionized to protest Google entering into agreement with the Pentagon. We've never seen this 19th-century union-style organization on 21st-century frontier AI before." },
    { speaker: "Alexander Wissner-Gross", tStart: "29:20", quote: "Within Google the three main compute consumers — search, cloud, DeepMind — have to fight out new compute capacity that comes online on a periodic basis. This is a preview of the future: per-token economic productivity gets prized, most revenue-generating tokens get the most compute." },
    { speaker: "Salim Ismail", tStart: "44:23", quote: "AI is not coming in through the CIO or CEO — it's going to come in through governance, top-down, forced into companies because there's too much internal resistance. PE becomes the main deployment channel for enterprise AI." },
    { speaker: "Alexander Wissner-Gross", tStart: "33:04", quote: "Microsoft wasn't in a position to supply enough compute for OpenAI's demands. As a result that marriage has turned into OpenAI dating everyone else at this point — Amazon, Google Cloud, Oracle. Stargate is no longer a buildout; it's a leasing brand." },
    { speaker: "Brian Elliott", tStart: "59:31", quote: "Sarah is probably right that OpenAI doesn't meet reporting standards for public companies. It's incredibly challenging to know what's going to happen three quarters from now and put your name behind it in a 10-K." },
  ],
  questions: [
    { id: "q1", kind: "recall", prompt: "Cite the three Alphabet quarter headlines, Google Cloud's growth rate, and how close Google is to Nvidia's market cap.",
      rubric: ["$109.9B total revenue (+22% YoY)", "$62.6B profit", "Google Cloud $20B (+63%) — beats AWS + Azure", "Within 4% of Nvidia's market cap", "3/4 billion monthly active users"],
      concepts: ["alphabet-109b-quarter", "google-cloud-beats-aws"] },
    { id: "q2", kind: "recall", prompt: "What seven categories of AI labs has the Pentagon contracted, and what was the labor response?",
      rubric: ["Google, SpaceX AI, OpenAI, Amazon, Microsoft + 2 more", "Google contract: 'any lawful government purpose'", "~600 Google employees protested (vs 20k for Project Maven 2018)", "DeepMind employees unionized for the first time", "Never seen union organizing on frontier AI"],
      concepts: ["pentagon-7-labs-contract"] },
    { id: "q3", kind: "applied", prompt: "Apply AWG's framing to the 'Mythos moment.' What specific capability triggered the White House pivot, and why does it matter?",
      rubric: ["Cyber-security / vulnerability discovery effectively solved", "Private sector leapfrogged NSA-level capability", "Solve-everything moment for one discipline", "Even AI-friendly administration must consider gatekeeping", "Precedent: Atomic Energy Act, Invention Secrecy Act, export controls"],
      concepts: ["mythos-moment-sea-change", "wh-prerelease-vetting"] },
    { id: "q4", kind: "applied", prompt: "Apply the 'per-token economic productivity' principle. How does Google ration compute INTERNALLY between search, cloud, and DeepMind?",
      rubric: ["Three units fight for monthly compute allocation", "Most revenue-generating tokens win the auction", "Search ad revenue still 90% of margin → priority", "DeepMind has to justify $/token vs cloud customers", "Liquid market for compute = future of every frontier shop"],
      concepts: ["alphabet-109b-quarter", "google-cloud-beats-aws"] },
    { id: "q5", kind: "applied", prompt: "Walk through the OpenAI → Microsoft → Amazon drift. What does it tell us about cloud-AI alignment in 2026?",
      rubric: ["Microsoft's $80B cap on data center spend created compute starvation", "Stargate evolved from buildout → leasing brand", "OpenAI signs $100B AWS deal + GCP + Oracle", "Microsoft's pivot: build own foundation model (struggling to read OpenAI files)", "Multi-cloud is now table stakes; exclusivity is dead"],
      concepts: ["openai-drifts-from-msft"] },
    { id: "q6", kind: "synthesis", prompt: "Synthesize Salim's 'PE as main deployment channel' thesis. Why is this how enterprise AI actually gets deployed?",
      rubric: ["Internal IT/CIO resistance too high to break top-down", "PE owns the cap table → can mandate transformation", "Anthropic $1.5B JV with Blackstone/Goldman/Hellman", "OpenAI $10B JV with TPG/Brookfield/Advent", "PE plugs holes in DCF as terminal-value collapses", "AWG's skeptic take: circular sales risk"],
      concepts: ["pe-firms-deploy-ai"] },
    { id: "q7", kind: "synthesis", prompt: "Synthesize the OpenAI IPO-delay signal. What does Sarah Friar's leak imply about expectations management?",
      rubric: ["Missed billion-WAU target end-of-2025", "Bet on consumer use → had to pivot to enterprise", "Lawsuit overhang during road-show window", "CFO admits company doesn't meet 10-K reporting standards yet", "Re-anchoring expectations lower to beat on shorter timescale", "IPO window: SpaceX → Anthropic; OpenAI risks being #3"],
      concepts: ["openai-drifts-from-msft"] },
    { id: "q8", kind: "pitch", prompt: "Pitch why the insurers dropping AI coverage is a CANARY for systemic risk — and what it implies for capital markets.",
      rubric: ["Insurers can't actuary a fast-changing risk", "Drops force enterprises to self-insure / reduce adoption", "Or: drives demand for new AI-native risk products", "Connect to Chamath's terminal value collapse thesis", "Connect to AWG's frontier-lab self-policing concern"],
      concepts: ["ai-insurance-drops", "wh-prerelease-vetting"] },
  ],
  badge: { id: "frontier-policy-analyst", name: "Frontier Policy Analyst", iconKey: "chart", rarity: "epic" },
  xp: 180,
};
