import type { Mission } from "@/lib/types";

export const google40bAnthropic: Mission = {
  id: "google-40b-anthropic",
  podcastId: "moonshots",
  branch: "ai",
  episodeTitle: "Google Invests $40B Into Anthropic, GPT-5.5 Drops, and Google Cloud Dominates",
  episodeShortTitle: "Google $40B, GPT-5.5 & Compute Wars",
  guests: ["Peter Diamandis", "Dave Blundin", "Salim Ismail", "Alexander Wissner-Gross"],
  releasedDate: "2026-04-30",
  episodeNumber: 252,  // estimated by back-counting from verified EP 255 (anthropic-spacex). Real numbering may differ if intermediate episodes weren't covered — override when known.
  duration: "2h 12m",
  difficulty: "Advanced",
  videoId: "RCbJKkG_mZs",
  summary:
    "15 major model releases in 8 weeks. Kimi K2.6 trained for $4.66M matches Opus 4.6. GPT-5.5 drops with 37-point context-reasoning jump, 40% fewer tokens, 60% less hallucination. Math is cooked — 1% Frontier Math Tier 4 gain per month. Google's 8th-gen TPUs (TPU8T training / TPU8i inference) — 3× faster, 80% better per-dollar. Google commits $40B to Anthropic at $350B valuation (1/3 the trillion-dollar secondary mark). Amazon counters with $33B + 5GW Trainium compute. Anthropic's compute now bottlenecked at TSMC. Project Deal shows Claude running a marketplace.",
  concepts: [
    { id: "fifteen-models-eight-weeks", label: "15 models in 8 weeks",  color: "amber"  },
    { id: "kimi-k26-446m-training",     label: "Kimi K2.6 trained for $4.66M",  color: "green"  },
    { id: "gpt-55-terminal-bench",      label: "GPT-5.5 terminal-bench leap",   color: "cyan"   },
    { id: "math-is-cooked",             label: "Math is cooked (1%/mo)",        color: "purple" },
    { id: "tpu-8-generation",           label: "Google TPU 8T/8i",              color: "cyan"   },
    { id: "google-40b-anthropic-stake", label: "Google → $40B into Anthropic",  color: "green"  },
    { id: "amazon-33b-trainium",        label: "Amazon $33B Trainium deal",     color: "purple" },
    { id: "tsmc-real-bottleneck",       label: "TSMC = the real bottleneck",    color: "amber"  },
  ],
  evidence: [
    { speaker: "Peter Diamandis", tStart: "03:25", quote: "15 major releases in only eight weeks. We're getting a pace of two major models per week. You've got to be retired and just focusing only on this to keep up." },
    { speaker: "Peter Diamandis", tStart: "14:51", quote: "Kimi K2.6 — a trillion-parameter open-weight model, 32B active, 300 parallel agents, native text/image/video, 30× less than the most capable closed models. Trained for a total of $4.66 million." },
    { speaker: "Alexander Wissner-Gross", tStart: "27:55", quote: "From GPT-5.4 Pro to 5.5 Pro, approximately a 2% leap on Frontier Math Tier 4 in 2 months. Approximately 1% per month gains on research-level math. Math is cooked. In 4-5 years all frontier math tier 4 problems get solved." },
    { speaker: "Demis Hassabis (quoted)", tStart: "29:35", quote: "It's a coin flip now on whether just the existing architecture scaled up solves everything. We need new breakthroughs — or maybe not." },
    { speaker: "Alexander Wissner-Gross", tStart: "34:08", quote: "Google now accounts for approximately a quarter of all the AI compute on the planet. And the TPUs themselves are being designed by TPUs — recursive self-improvement goes all the way down to the silicon." },
    { speaker: "Dave Blundin", tStart: "39:09", quote: "It's all bottlenecked at TSMC. You can all partner with each other up the yin-yang, but whose chips actually get made? Only Elon will talk about it. The fundamental constraint is the Terafab." },
    { speaker: "Alexander Wissner-Gross", tStart: "53:30", quote: "Anthropic doesn't want to be triggering SaaS apocalypses left and right — there's relatively little economic motivation. All of their projects can be explained by one principle: maximize the economic value per token." },
    { speaker: "Alexander Wissner-Gross", tStart: "07:42", quote: "Noam Brown is pondering whether the weights actually matter as much as they used to, or whether it's really turning into a race for compute as inference-time reasoning becomes more important." },
  ],
  questions: [
    { id: "q1", kind: "recall", prompt: "Quantify Kimi K2.6 fully: params, active, agents, cost vs closed, total training cost.",
      rubric: ["1T total params, 32B active", "300 parallel agents", "Native text/image/video", "30× less than closed peers per token", "Total $4.66M training cost", "Backed by $4.7B from Alibaba/Tencent/IDG"],
      concepts: ["kimi-k26-446m-training"] },
    { id: "q2", kind: "recall", prompt: "GPT-5.5 headline numbers: context, token efficiency, hallucination, and pricing vs 5.4.",
      rubric: ["1M token context window with full long-context recall", "37-pt jump in long-context reasoning", "40% fewer tokens at same latency", "60% less hallucination", "Pricing: $5/$30 per M (in/out) — 2× of 5.4"],
      concepts: ["gpt-55-terminal-bench"] },
    { id: "q3", kind: "applied", prompt: "Apply AWG's 'math is cooked' extrapolation. What's the implication for research math jobs over 4-5 years?",
      rubric: ["1% gain per month on Frontier Math Tier 4", "Approaching ~50% solved today", "Linear extrapolation → all problems solved in ~50 months", "Acceleration likely → faster", "Implications: research math collapses to AI orchestration"],
      concepts: ["math-is-cooked"] },
    { id: "q4", kind: "applied", prompt: "Apply Noam Brown's 'weights matter less' framing. Why does sparsity / MoE / iterated amplification compound this?",
      rubric: ["Sparsity = only fraction of weights fire per query", "MoE = 32 of 1000B params used per token", "Reasoning over compute > raw param count", "Space-time transformer rolled out over reasoning tokens", "Weights commoditize → compute becomes the moat"],
      concepts: ["gpt-55-terminal-bench", "kimi-k26-446m-training"] },
    { id: "q5", kind: "applied", prompt: "Map the Google compute stack as a vertically integrated moat. Why is it harder to disrupt than Nvidia/OpenAI?",
      rubric: ["Own TPU silicon (3× faster, 80% better/$)", "Own data centers + GCP cloud", "Own frontier models (Gemini)", "Owns DeepMind R&D", "~25% of global AI compute", "Cash flow funds the next 100B bet"],
      concepts: ["tpu-8-generation", "google-40b-anthropic-stake"] },
    { id: "q6", kind: "synthesis", prompt: "Synthesize the Google $40B / Amazon $33B Anthropic deals. Why do BOTH hyperscalers want exposure, at deep discounts?",
      rubric: ["$350B valuation vs $1T secondary → 1/3 discount", "Hyperscalers buying every horse in the race", "Anthropic gets 5GW each = total 10GW of compute", "Cash-for-compute swap (Anthropic spends $100B+ on AWS)", "Compute > marketshare in the singularity"],
      concepts: ["google-40b-anthropic-stake", "amazon-33b-trainium"] },
    { id: "q7", kind: "synthesis", prompt: "Synthesize the 'TSMC bottleneck' thesis. Why does Dave argue Elon's Terafab is the only honest fix?",
      rubric: ["All hyperscalers depend on TSMC + Samsung + Intel", "Capacity is finite even if money is infinite", "Energy is co-binding (powered-land permitting)", "Terafab = 50× the planet's current chip output", "Vertical sovereignty for the AI stack"],
      concepts: ["tsmc-real-bottleneck"] },
    { id: "q8", kind: "pitch", prompt: "Pitch the 'value-per-token' framework to a frontier-lab CEO making product roadmap decisions.",
      rubric: ["Don't chase consumer use (cheap tokens)", "Concentrate on enterprise / codegen (expensive tokens)", "Every product = bid for limited compute, choose highest $/token", "Project Deal-style experiments reveal token-value per use-case", "Self-cannibalization: kill anything <Xth-percentile $/token"],
      concepts: ["fifteen-models-eight-weeks", "google-40b-anthropic-stake"] },
  ],
  badge: { id: "model-race-cartographer", name: "Model-Race Cartographer", iconKey: "brain", rarity: "epic" },
  xp: 180,
};
