import type { Mission } from "@/lib/types";

export const googleIoKarpathyCerebras: Mission = {
  id: "google-io-karpathy-cerebras",
  podcastId: "moonshots",
  branch: "ai",
  episodeTitle: "Google I/O 2026, Karpathy Joins Anthropic, and Cerebras' $95B IPO",
  episodeShortTitle: "Google I/O, Karpathy → Anthropic & Cerebras $95B",
  episodeNumber: 256,
  guests: ["Peter Diamandis", "Dave Blundin", "Salim Ismail", "Alexander Wissner-Gross", "Andrew Feldman"],
  releasedDate: "2026-05-21",
  duration: "2h 23m",
  difficulty: "Advanced",
  videoId: "kklrodAua_U",
  summary:
    "Annual Google I/O recap. Google CapEx 6x in 4 years: $31B (2022) → $180-190B (2026). Now processing 3.2 quadrillion tokens/month (vs 9.7T two years ago) and 19B tokens/min via API. 13 products with 1B+ users each, 5 with 3B+. Gemini app at 900M MAU, AI mode at 1B+ MAU in a year. 1M-TPU cluster online, new TPUs 2x perf/watt. Gemini Omni launched — generative video native to the Gemini app, plus world models and interactive sim. Gemini 3.5 Flash is throughput- and tool-use-maxed (still behind GPT 5.5 high / X high on raw frontier); 3.5 Pro 'in another month.' SynthID watermarking now covers 100B+ images and 60K years of audio — OpenAI, Nvidia, Eleven Labs, Kakao all adopt. Industry self-regulating ahead of Congress. Anti-gravity 2.0 (the Windsurf rebrand) and Gemini Spark (Google's Open Claw competitor) ship as fast-follower products leaning on default-behavior distribution. AI Search Mode reimagines the search box, with AI suggestions that can drift queries toward more profitable ad results. Universal Cart works across Nike/Target/Walmart/Shopify — CMOs now market to AGENTS, not humans. Audio-only smart glasses with Samsung + Warby Parker + Gentle Monster (Google ceded smart glasses to Meta). Demis: 'foothills of the singularity' — Gemini for Science with weather-next, Isomorphic Labs preclinical drugs. $2M Build with Gemini X-Prize launched. Andre Karpathy joins Anthropic to use Claude to accelerate Claude's own pre-training — recursive self-improvement. Federal jury rejects Elon's OpenAI lawsuit in 2 hours (statute of limitations). Cerebras IPO: $5.5B raised, +68% pop, $95B market cap — third-largest US tech IPO ever. Andrew Feldman details the wafer-scale bet: 15-20x faster than GPU on inference, Kimi K2 trillion-param at 1000 tok/s vs 70 on Fireworks. Feldman on Terafab: 15-20 year project, not 5-10. China leading on power infra but compute-starved; running proxy services selling American tokens at 10x discount to siphon reasoning traces.",
  concepts: [
    { id: "google-capex-6x",          label: "Google CapEx 6x to $180-190B",        color: "amber"  },
    { id: "gemini-omni-multimodal",    label: "Gemini Omni — only US multimodal bet", color: "purple" },
    { id: "gemini-spark-fast-follower", label: "Gemini Spark = Open Claw fast-follower", color: "cyan"   },
    { id: "synthid-industry-self-reg", label: "SynthID + industry self-regulation",  color: "green"  },
    { id: "karpathy-anthropic-rsi",    label: "Karpathy → Anthropic for recursive self-improvement", color: "purple" },
    { id: "cerebras-95b-ipo",          label: "Cerebras $95B IPO + wafer-scale moat", color: "cyan"   },
    { id: "feldman-terafab-15yr",      label: "Feldman: Terafab is a 15-20 year project", color: "amber" },
    { id: "intent-agent-transaction",  label: "Intent → Agent → Transaction shopping", color: "green" },
  ],
  evidence: [
    { speaker: "Sundar Pichai", tStart: "05:42", quote: "Two years ago we were processing 9.7 trillion tokens a month. Last year at I/O that grew to 480 trillion. Today that number has jumped seven times to 3.2 quadrillion tokens per month. In 2022 we were spending $31 billion annually in CapEx — this year approximately $180 to $190 billion." },
    { speaker: "Alexander Wissner-Gross", tStart: "15:33", quote: "I want to applaud Demis and Google DeepMind for being the only arguably remaining American frontier lab to still be chasing multimodality. OpenAI cut Sora and deemphasized video. Anthropic has never been chasing multimodality — they've been squarely focused on CodeGen. That just leaves Google with the only credible frontier American video model." },
    { speaker: "Dave Blundin", tStart: "22:50", quote: "The scuttlebutt here in Silicon Valley is that it's a two-horse race between OpenAI and Anthropic for the best AI in the world and the talent is flooding into those two buildings in SF. Nothing in that demo or in the vibe on campus at Google contradicts that." },
    { speaker: "Salim Ismail", tStart: "29:00", quote: "When you have intelligence becoming abundant, then the scarcity goes towards trust. We may end up at a point where authenticity is more valuable than creativity. We're moving from the information age to the verification age, and trust is becoming infrastructure." },
    { speaker: "Dave Blundin", tStart: "53:54", quote: "Anything can slow down Google because of their massive distribution advantage. They don't have to push the outer boundary — they can afford to be fast follower. They just need to be as good one day later and integrated with Chrome, Search, Android, and they will win." },
    { speaker: "Andre Karpathy", tStart: "01:25:32", quote: "I've joined Anthropic. The next few years at the frontier of LLMs will be especially formative. I'm very excited to join the team and remain deeply passionate about education. If you're outside of that frontier lab, your judgment fundamentally will start to drift." },
    { speaker: "Andrew Feldman", tStart: "01:38:35", quote: "In December 2025 we signed a deal with OpenAI north of $20 billion over several years — one of the largest deals ever signed in Silicon Valley. In March we signed a term sheet with AWS for deployment in their data centers. Yesterday we posted numbers on Kimi K2, a trillion-parameter model — about 1,000 tokens per second where a really good GPU shop like Fireworks runs at 70." },
    { speaker: "Andrew Feldman", tStart: "01:48:28", quote: "Building fabs is very hard. It is hard in a different way than some of the other problems Elon has attacked. I'm not saying he can't do it. I'm saying it will always take longer than he says, cost vastly more money. This is not a 5 or 10-year project in my humble view. I put this at a 15 or 20-year project." },
  ],
  questions: [
    { id: "q1", kind: "applied", prompt: "Apply Dave's 'fast follower with distribution' thesis to Google's Gemini Spark vs Open Claw. Why might the technically inferior product still win 80% of the market?",
      rubric: ["Open Claw needs explicit install + onboarding (high friction)", "Gemini Spark is one click away from Search/Chrome/Android (default behavior)", "Microsoft-vs-Netscape parallel — distribution beat technical lead", "13 Google products with 1B+ users each = installed base", "Spark trains hundreds of millions of users on agentic workflows", "Even an inferior product wins if the cost of switching exceeds the quality gap"],
      concepts: ["gemini-spark-fast-follower"] },
    { id: "q2", kind: "synthesis", prompt: "Synthesize Salim's 'scarcity = abundance minus trust' framing against Google's SynthID push. Why is this BIGGER than just a watermark?",
      rubric: ["Cost of generating content collapses → value shifts to filtering + authenticity", "Industry self-regulates because Congress can't keep up with AI velocity", "OpenAI/Nvidia/Eleven Labs/Kakao all adopt = standards emerge bottom-up", "Information age → Verification age — trust becomes the new scarce asset", "End-to-end cryptographic proof of reality (synthetic-side, not capture-side)", "Whoever owns trust infrastructure captures the next layer of value"],
      concepts: ["synthid-industry-self-reg"] },
    { id: "q3", kind: "applied", prompt: "Apply the 'multimodality is a contrarian bet' framing. Why might Google DeepMind be RIGHT to keep chasing video + biological sequences while OpenAI and Anthropic cut Sora and skip multimodality entirely?",
      rubric: ["Modality scaling thesis — superintelligence emerges from cross-modal generalization", "Treating DNA/protein as just another modality opens scientific discovery", "Consumer demand for video is the largest untapped attention pool", "Chinese labs (Sea Dance 2.0, Kling) prove video is winnable with data", "OpenAI/Anthropic concentrating on enterprise + codegen leaves consumer video open", "Idiosyncratic bet — but the payoff if right is uncontested"],
      concepts: ["gemini-omni-multimodal"] },
    { id: "q4", kind: "synthesis", prompt: "Synthesize Karpathy's move to Anthropic and the 'recursive self-improvement' framing. What does this signal about where the frontier actually lives?",
      rubric: ["Karpathy's quote: 'if you're outside that frontier lab, your judgment will drift'", "He joined the pre-training team to use Claude to improve Claude itself — RSI loop", "Anthropic over OpenAI/Google = ethical positioning matters in talent attraction", "Two-horse race confirmed: OpenAI and Anthropic; Google running #3", "Investors increasingly want the RSI bar — codegen → next-gen of codegen", "The frontier isn't in papers anymore — it's in unpublished iterations inside two buildings"],
      concepts: ["karpathy-anthropic-rsi"] },
    { id: "q5", kind: "applied", prompt: "Apply Andrew Feldman's wafer-scale architecture argument. Why does a 'chip the size of a dinner plate' beat clusters of small GPUs at trillion-param inference?",
      rubric: ["SRAM (fast) vs DRAM/HBM (slow) — wafer-scale stuffs SRAM to the gills", "Single chip = fewer hops between layers, less interconnect penalty", "Groq has to split a model across 2-3k chips (each hop hurts)", "Cerebras splits across 4-8 chips, each layer fully on-chip", "100GbE between chips is fast enough when most calculation stays local", "Result: ~1000 tok/s on Kimi K2 vs 70 on best GPU shop = 15x advantage"],
      concepts: ["cerebras-95b-ipo"] },
    { id: "q6", kind: "synthesis", prompt: "Synthesize Feldman's 'Terafab = 15-20 years' verdict against Elon's announced timeline. What is Feldman seeing that Elon's plan ignores?",
      rubric: ["Fabs require an entire surrounding ecosystem (packaging, materials, deposition)", "Even ASML-equipped fabs (Samsung, TSMC) aren't at the same node — institutional learning matters", "Cross-administration political risk for any 5+ year project", "Local ordinances (Samsung Texas redesigned for a fire rule) compound delays", "TSMC Arizona is already badly behind schedule despite a decade of effort", "Feldman: 'if anybody can do it Elon can — but it will cost vastly more and take longer'"],
      concepts: ["feldman-terafab-15yr"] },
    { id: "q7", kind: "applied", prompt: "Apply Salim's 'Intent → Agent → Transaction' framing to Universal Cart. What gets disrupted, and what new business is created?",
      rubric: ["Old flow: Human → Website → Cart → Checkout", "New flow: Intent → Agent → Transaction (no browsing layer)", "Every CMO now markets to 100M agents, not humans — agent SEO becomes a category", "Returns become surprise-and-delight — agent ships, you keep or send back", "Trillion-dollar company emerges from helping AGENTS choose products", "Brand + MTP + proprietary data become the only moats agents respect"],
      concepts: ["intent-agent-transaction"] },
    { id: "q8", kind: "pitch", prompt: "Pitch the bull case for Cerebras at $95B post-IPO. Why is this a multi-trillion outcome, not a meme top?",
      rubric: ["OpenAI $20B+ multi-year deal + AWS term sheet = signed demand", "15x faster than GPU on inference — and inference is now 80-90% of compute spend", "Wafer-scale solved fault tolerance + thermal expansion years ahead of Nvidia's CoWoS struggle", "Anthropic, OpenAI, Macrohard all bottlenecked on inference throughput per user (not aggregate)", "Space data centers: wafer-scale fault tolerance is the perfect ionizing-environment computer", "Feldman: 'pyramid' moat — building this took 4 years and $500M; nobody else has the institutional learning"],
      concepts: ["cerebras-95b-ipo", "feldman-terafab-15yr"] },
  ],
  badge: { id: "google-revival-strategist", name: "Google Revival Strategist", iconKey: "brain", rarity: "epic" },
  xp: 200,
};
