import type { Mission } from "@/lib/types";

export const muskVsAltman: Mission = {
  id: "musk-vs-altman",
  podcastId: "moonshots",
  branch: "ai",
  episodeTitle: "Elon Musk vs. Sam Altman, AI Job Loss, and OpenAI's $852B Valuation",
  episodeShortTitle: "Musk vs. Altman & The $852B Lawsuit",
  guests: ["Peter Diamandis", "Dave Blundin", "Salim Ismail", "Alexander Wissner-Gross"],
  releasedDate: "2026-04-14",
  episodeNumber: 247,  // estimated by back-counting from verified EP 255 (anthropic-spacex). Real numbering may differ if intermediate episodes weren't covered — override when known.
  duration: "2h 05m",
  difficulty: "Advanced",
  videoId: "5ak26W2YNRY",
  summary:
    "xAI rebuilds under SpaceX VP of Starlink leadership before SpaceX IPO. Colossus 2 training 7 models including a 10T parameter giant (parameter ceiling stuck at 10T). Musk sues OpenAI $100B — wants Altman/Brockman out + nonprofit reversion. Brockman's 2017 diary entry surfaces in discovery as smoking gun. Anthropic projected to hit $100B ARR EOY 2026, $1T by EOY 2027 ($40T valuation). Claude managed agents launches. OpenAI hits $852B valuation on $122B raise (Amazon $50B / Nvidia $30B / SoftBank $30B / retail $3B). Q1 2026 global VC AI investment hits $242B — 64% concentrated in OpenAI/Anthropic/xAI/Waymo. AI super-PAC raises $100M heading to $300M. Marc Andreessen rebukes AI job-loss narratives. Meta launches Claude-onomics leaderboard.",
  concepts: [
    { id: "musk-altman-100b-suit",     label: "$100B Musk-Altman lawsuit",      color: "amber"  },
    { id: "openai-852b-valuation",     label: "OpenAI $852B / $122B raise",     color: "purple" },
    { id: "anthropic-100b-arr-projection", label: "Anthropic $100B ARR projection", color: "green" },
    { id: "claude-managed-agents",     label: "Claude managed agents",          color: "cyan"   },
    { id: "colossus-2-seven-models",   label: "Colossus 2 — 7 models, up to 10T params", color: "cyan"   },
    { id: "parameter-ceiling-plateau", label: "10T parameter ceiling holds",    color: "green"  },
    { id: "vc-242b-quarter",           label: "$242B VC into AI Q1, $3B/day",   color: "amber"  },
    { id: "claude-onomics-leaderboard", label: "Claude-onomics token leaderboards", color: "purple" },
  ],
  evidence: [
    { speaker: "Peter Diamandis", tStart: "15:31", quote: "Musk has sued OpenAI for $100 billion against Altman and Brockman — accused of fraud, breach of contract. He's asking for Altman and Brockman to step down and reverting to nonprofit." },
    { speaker: "Peter Diamandis", tStart: "19:55", quote: "The case gained momentum when discovery revealed Greg Brockman's 2017 diary entry: 'We truly want the BC Corp. The true answer is that we want Elon out. If three months later we're doing a BBC Corp, then it was a lie.'" },
    { speaker: "Alexander Wissner-Gross", tStart: "11:09", quote: "Going up to 10 trillion parameters versus 1 trillion — the parameter scaling race seems to be over. We've plateaued. In part due to reasoning, in part due to distillation." },
    { speaker: "Peter Diamandis", tStart: "27:29", quote: "Anthropic ARR projected to reach $100B by end of 2026 and a trillion by end of 2027. At 20× revenue multiple, that's a $2-7T valuation EOY 2026, $40T at trillion ARR. The numbers are insane." },
    { speaker: "Salim Ismail",   tStart: "29:21", quote: "Claude managed agents is a huge pivot from AI that answers to AI that does. Real bridge between LLMs and enterprise ROI. Shifts economic gravity from software licensing to outcomes — this is the organizational singularity." },
    { speaker: "Peter Diamandis", tStart: "01:02:21", quote: "Global VC investments in AI hit a record $242B in Q1 2026 — outdoing all of 2025. 64% concentrated in OpenAI, Anthropic, xAI, Waymo. $3 billion a day being invested in AI." },
    { speaker: "Alexander Wissner-Gross", tStart: "01:40:00", quote: "Investors increasingly don't just want an AI startup — they want a recursively self-improving AI startup. Building better versions of themselves using what they have right now. OpenAI, Anthropic, xAI, Waymo all pass that bar." },
    { speaker: "Dave Blundin", tStart: "01:51:00", quote: "We've already implemented Claude-onomics targets across all our companies. Targeting 80% token cost, 20% salary. Be in the 20% of payroll left when the 80% token regime arrives — improving AI by 1% is worth more than cost-cutting the last humans." },
  ],
  questions: [
    { id: "q1", kind: "recall", prompt: "What three remedies is Musk seeking, and what's Brockman's smoking-gun diary entry?",
      rubric: ["Altman and Brockman step down", "Revert OpenAI to nonprofit", "$100B damages", "Brockman diary: 'we want Elon out', 'if three months later we're doing a BBC Corp, then it was a lie'", "Allowed judge to let case proceed"],
      concepts: ["musk-altman-100b-suit"] },
    { id: "q2", kind: "recall", prompt: "OpenAI's $122B raise: who put in what, and what was the AGI clause?",
      rubric: ["$50B Amazon (AGI clause — investment changes if AGI is reached)", "$30B Nvidia", "$30B SoftBank", "$3B retail investors", "$852B post-money valuation"],
      concepts: ["openai-852b-valuation"] },
    { id: "q3", kind: "applied", prompt: "Apply AWG's '10T parameter ceiling = end of pure parameter scaling' argument. What now drives capability?",
      rubric: ["Frontier labs no longer disclose params", "1T was prior soft ceiling — still intact 2+ years later", "Reasoning + distillation + iterated amplification drive capability now", "Compute flows to inference-time reasoning", "AWG: weights may even matter less than raw compute (Noam Brown thesis)"],
      concepts: ["parameter-ceiling-plateau", "colossus-2-seven-models"] },
    { id: "q4", kind: "applied", prompt: "Apply the 'recursively self-improving AI startup' bar. Who passes and why?",
      rubric: ["OpenAI / Anthropic / xAI — codegen → next gen of code", "Waymo — models steer cars to maximize information gain (RSI)", "Bar is now beyond 'just an AI startup'", "Investor capital pours into RSI loops disproportionately", "Implies kill-shot for non-RSI AI startups"],
      concepts: ["vc-242b-quarter"] },
    { id: "q5", kind: "applied", prompt: "Apply the Anthropic ARR projection. Why does Dave think $100B EOY is achievable but $1T 2027 is implausible?",
      rubric: ["$100B feasible at 80× growth velocity", "$1T requires another 10× in one year — historically unprecedented", "Compute-constrained ceiling", "More realistic: $300-500B mid-2027", "Even then implied valuation > Apple"],
      concepts: ["anthropic-100b-arr-projection"] },
    { id: "q6", kind: "synthesis", prompt: "Synthesize the IPO-window dynamics. Why is sequencing SpaceX → Anthropic → OpenAI critical?",
      rubric: ["Capital supply is finite (UBS CIO: must sell something else to fund IPOs of this size)", "Going #1 sucks oxygen — soaks up global liquidity", "SpaceX = $2T June, Anthropic next, OpenAI delayed by lawsuit", "Being IPO #3 = risk of insufficient capital", "Sarah Friar's leaked IPO-delay-to-2027 = expectation re-anchoring"],
      concepts: ["openai-852b-valuation", "musk-altman-100b-suit"] },
    { id: "q7", kind: "synthesis", prompt: "Synthesize Dave's 80/20 token-to-salary framework. Why is it more than cost-cutting?",
      rubric: ["Target: 80% spend on AI compute, 20% on humans", "Token spend = first legible per-employee productivity metric", "Capture all prompt history (S3/Bedrock) before employees self-host", "AI audits the tokens — gamesmanship resistant", "Be in the 20% of payroll that remains — 1% AI improvement > last cost cut"],
      concepts: ["claude-onomics-leaderboard"] },
    { id: "q8", kind: "pitch", prompt: "Pitch why Marc Andreessen's 'AI job-loss narratives are fake' framing might actually be CORRECT for 2030 even if devastating short-term.",
      rubric: ["Andreessen: AI = productivity ramp → demand ramp → jobs boom", "Net jobs may rise even as categories collapse (Industrial Revolution parallel)", "Internal company AI adoption is SLOW (years) — transition smooths shock", "Salim: 4-5× more companies created, 25% the headcount per company", "AWG: net jobs ≥ flat, but full of exotic new role categories"],
      concepts: ["vc-242b-quarter"] },
  ],
  badge: { id: "ai-governance-analyst", name: "AI Governance Analyst", iconKey: "brain", rarity: "epic" },
  xp: 180,
};
