import type { Mission } from "@/lib/types";

export const spacexIPO: Mission = {
  id: "spacex-ipo",
  podcastId: "moonshots",
  branch: "space",
  episodeTitle: "SpaceX Goes Public, Claude's Mythos Release, and the US Data Center Delay",
  episodeShortTitle: "SpaceX $2T IPO, Artemis II & Mythos",
  guests: ["Peter Diamandis", "Dave Blundin", "Salim Ismail", "Alexander Wissner-Gross"],
  releasedDate: "2026-04-11",
  episodeNumber: 246,  // estimated by back-counting from verified EP 255 (anthropic-spacex). Real numbering may differ if intermediate episodes weren't covered — override when known.
  duration: "2h 22m",
  difficulty: "Advanced",
  videoId: "cFI-SqnvQK8",
  summary:
    "SpaceX prices at $2T — largest IPO in history. Starlink = 75-80% of value, not rockets. Artemis II returns humans beyond the moon for the first time in 54 years; Crew of Wiseman/Glover (first African-American)/Koch (first woman)/Hansen circumlunar mission. Four space missions inbound: VIPER, Escapade, SR1 Freedom nuclear-electric, Dragonfly to Titan, Europa Clipper to Jupiter. Mythos drops with strongly superhuman cyber-security vulnerability discovery — Anthropic launches Glasswing coalition to defend codebases. Polymarket gives Mythos release 7% by month's end. GPT-5.5 'Spud' imminent. DeepSeek V4 + Gemma 4 (4B params, runs on iPhone). Anthropic overtakes OpenAI in ARR. $300B data-center capex crunch.",
  concepts: [
    { id: "starlink-dominates-valuation", label: "Starlink = 75–80% of SpaceX",  color: "cyan"   },
    { id: "ipo-wars-2026",                label: "IPO wars: SpaceX → OpenAI → Anthropic", color: "amber" },
    { id: "artemis-ii-crewed-moon",       label: "Artemis II — first crewed beyond moon in 54yrs", color: "cyan" },
    { id: "nuclear-electric-deep-space",  label: "Nuclear-electric interplanetary propulsion", color: "purple" },
    { id: "mythos-glasswing-coalition",   label: "Mythos + Glasswing coalition",  color: "purple" },
    { id: "demand-not-supply-unlocked",   label: "Demand-side unlock (AWG)",      color: "green"  },
    { id: "deepseek-gemma-cheap-ai",      label: "DeepSeek V4 / Gemma 4 ultra-cheap", color: "green" },
    { id: "anthropic-overtakes-openai",   label: "Anthropic overtakes OpenAI ARR", color: "cyan"  },
  ],
  evidence: [
    { speaker: "Peter Diamandis", tStart: "04:14", quote: "SpaceX is pricing itself at about a $2 trillion target valuation, raising $75 billion. The vast majority of the value today is Starlink — 75-80% of the target valuation. 15-18% launch services, 5% NASA services." },
    { speaker: "Alexander Wissner-Gross", tStart: "30:18", quote: "It's an enormous shame for civilization that we went for more than half a century without doing what we did in the 70s. I'm utterly paranoid the same thing could happen with AI — that we're on the precipice of broadly available superintelligence and just take a 54-year pause." },
    { speaker: "Alexander Wissner-Gross", tStart: "43:00", quote: "The killer app of compact fusion reactors won't be data centers on land or in orbit — it's going to be for interplanetary, maybe even interstellar propulsion. The dawn of nuclear-electric deep space exploration." },
    { speaker: "Alexander Wissner-Gross", tStart: "55:21", quote: "We officially have models smart enough to break out of their environments and then apologize for it. Mythos at 400× human productivity on long-horizon AI research tasks. The strongest model we've ever seen from any frontier lab." },
    { speaker: "Dave Blundin", tStart: "57:48", quote: "Mythos in cyber-attack mode would be the best cyber-attacker in the history of the world if put in the wrong hands. Polymarket dropped from 80% → 7% chance of release within the month. The golden era of frontier AI access may be ending." },
    { speaker: "Alexander Wissner-Gross", tStart: "10:46", quote: "It's not that supply has been unlocked. Demand has been unlocked. Elon announced the SpaceX IPO the moment orbital data centers became obvious. If municipalities welcomed land-based DCs with open arms, the PE multiple would compress materially." },
    { speaker: "Peter Diamandis", tStart: "01:08:00", quote: "Anthropic at $30B ARR overtakes OpenAI at $24-25B. Open AI Sora shuts down — losing $1M/day in compute, killing the Disney deal. Sam pivots back to enterprise core." },
    { speaker: "Alexander Wissner-Gross", tStart: "01:25:00", quote: "DeepSeek V4 — trillion-param, 37B active per token, 10-50× cheaper than GPT-5.4 and Opus 4.6. Gemma 4 is 4B params and runs on your iPhone offline. The intelligence-spread story is more important than the frontier story." },
  ],
  questions: [
    { id: "q1", kind: "recall", prompt: "Decompose the SpaceX $2T valuation by source. What share comes from which line, and what's the 2025 revenue/profit baseline?",
      rubric: ["~75-80% Starlink", "~15-18% Launch services", "~5% NASA services", "X/xAI = future potential", "2025: $16B revenue, $8B profit (~50% margin)", "Doubling to $20B in 2026"],
      concepts: ["starlink-dominates-valuation"] },
    { id: "q2", kind: "recall", prompt: "Name the Artemis II crew of four and what the mission accomplishes. What's the planned Artemis III/IV cadence?",
      rubric: ["Reid Wiseman (commander)", "Victor Glover (first African-American)", "Christina Koch (first woman)", "Jeremy Hansen (Canadian SA)", "Artemis II = circumlunar Apollo-8 style", "Artemis III in 2027 = LEO rendezvous test with Starship HLS", "Artemis IV early 2028 = crewed south pole landing"],
      concepts: ["artemis-ii-crewed-moon"] },
    { id: "q3", kind: "recall", prompt: "Name four upcoming deep-space missions and their target.",
      rubric: ["VIPER — south pole moon rover (ice hunt)", "Escapade — Mars magnetosphere", "SR1 Freedom — nuclear-electric interplanetary with 3 helicopters on Mars", "Dragonfly — nuclear-electric octocopter to Titan (2034)", "Europa Clipper — Jupiter 2030, 50 passes near Europa"],
      concepts: ["nuclear-electric-deep-space"] },
    { id: "q4", kind: "applied", prompt: "Apply AWG's 'demand-side unlock' framing. What's the counterfactual to land-based DC permitting hostility?",
      rubric: ["If states/feds welcomed DCs + on-site fission/solar, orbital PE compresses", "Orbital is being priced because terrestrial permitting is broken", "Demand was unlocked the moment orbital DCs became obvious", "NIMBY response in Maine, Ohio, Missouri forces the orbital pivot"],
      concepts: ["demand-not-supply-unlocked"] },
    { id: "q5", kind: "applied", prompt: "Apply the AGI-equivalent of AWG's 54-year-gap paranoia. Why is the post-Apollo civilizational gap a warning sign?",
      rubric: ["Civilization unwound progress on most important spatial dimension", "Lack of political will + funding shift (space shuttle = jobs program)", "Apollo budget = 2% GDP vs NASA today ~0.1%", "Wealth now concentrated enough to bypass government", "Same could happen with AI if frontier labs self-police too aggressively"],
      concepts: ["artemis-ii-crewed-moon", "nuclear-electric-deep-space"] },
    { id: "q6", kind: "synthesis", prompt: "Synthesize the Mythos release dilemma. Why did Polymarket drop from 80% → 7% release probability?",
      rubric: ["March 31 hack revealed Mythos-class cyber risk publicly", "Anthropic uses agentic-misalignment + bio-threat + cyber threshold for release", "Cyber threats hard to gatekeep — same skill = code generation", "Glasswing coalition + controlled disclosure precedent vs full release", "Sets up the OpenAI / xAI competitive pressure question for next release"],
      concepts: ["mythos-glasswing-coalition"] },
    { id: "q7", kind: "synthesis", prompt: "Synthesize Anthropic overtaking OpenAI in ARR. What's the underlying strategic divergence?",
      rubric: ["Anthropic at $30B ARR vs OpenAI at $24-25B", "OpenAI bet consumer (Sora cancelled, Disney $1B killed)", "Anthropic bet enterprise from day one (Claude Code, Co-work)", "Per-token economic value > raw user count", "OpenAI's pivot back to enterprise is expensive catch-up"],
      concepts: ["anthropic-overtakes-openai", "ipo-wars-2026"] },
    { id: "q8", kind: "pitch", prompt: "Pitch retail SpaceX IPO participation despite the 109× PE. Tie it to Elon's stepping-stone vision and the Google IPO prospectus parallel.",
      rubric: ["Starlink → orbital DCs → moon → Mars stepping stones", "Founder access to public markets = capital flywheel", "Google IPO prospectus vastly underplayed actual outcome", "Don't bet against Elon's math — never been short an Elon mission", "Math checks out at projected launch cadence + 10× global GDP growth"],
      concepts: ["ipo-wars-2026"] },
  ],
  badge: { id: "spacex-ipo-scout", name: "Orbital Capital Scout", iconKey: "rocket", rarity: "epic" },
  xp: 180,
};
